import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/MainNav";
import QuarterCircleNavigation from "@/components/QuarterCircleNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-aqua`}>
        <main className="flex min-h-screen flex-col items-center justify-between p-0 bg-gradient-to-br from-primary to-secondary">
          <div className="z-10 max-w-100 w-full items-center justify-between font-mono text-sm lg:flex flex-col">
            <Navigation />
            <QuarterCircleNavigation />
            <div className="z-10 max-w-100 w-full items-center justify-between font-mono text-sm lg:flex p-24">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
